name: Unit Tests - MacOS
on:
# manual trigger
  workflow_dispatch:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: macos-latest
    name: Unit Tests
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Build and test
      run: |
        dotnet build -c Release /p:TreatWarningsAsErrors=true /p:RunAnalyzers=true
        dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj
